export interface TransactionDtDto{
    tenentId: number;
    locationId: number;
    mytransid: number;
    myid: number;
    employeeId: number;
    installmentNumber: number;
    attachId: number;
    periodCode: number;
    installmentAmount: number;
    receivedAmount: number;
    pendingAmount: number;
    discountAmount: number;
    discountReference: string;
    universityBatchNo: string;
    receivedDate: Date;
    effectedAccount: string;
    otherReference: string;
    activityid: number;
    crupId: number;
    glpost: string;
    glpost1: string;
    glpostref1: string;
    glpostref: string;
    active: boolean;
    switch1: string;
    delFlag: number;
    remark: String;
}